// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "quit_porn",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "quit_porn",
            targets: ["AppModule"],
            bundleIdentifier: "com.architkumar.quitporn",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources/Bloom",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
